### ISSUE TITLE
Can you support Ubuntu?

### ISSUE THREAD

**Issue by bilelmoussaoui** [serge1peshcoff/photostream#1]
I know that you've made the app only for elementary os ;
could you make it possible for us to use it on ubuntu 14.04/14.10??
i tried to built it from the sources and i've get this; if it might help you ;)
--   package 'granite' not found
--   package 'json-glib-1.0' not found
--   package 'webkit2gtk-4.0>=2.6.4' not found
--   package 'libnotify' not found

Thank you !

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui as I see, the only dependency from elementary OS here is granite, and I'll try to make it work without granite a little bit later.
Other dependencies are:
- json-glib-1.0 is in Ubuntu package libjson-glib-1.0-0 and libjson-glib-dev 
- libnotify is in Ubuntu package libnotify-dev (as I understood)
- webkit2gtk-4.0 is not in Ubuntu packages and at the moment you have to compile it yourself (but I'll make the deb package when I'll publish it).

Thanks for the reply :)

**Comment by bilelmoussaoui** [comment]
Thank you so much! i will really appreciate the possibility to check my instagram on my pc without going to the official site ;) 
Keep up the great work

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui thanks a lot ;)

**Comment by bilelmoussaoui** [comment]
Its works now without granite , i've tried to build webkit2gtk, and i think that i've succed.. but whenever i try to build your app i end up with this error message : 
--   package 'webkit2gtk-4.0>=2.6.4' not found
and in the official website th last version is 2.6.4?

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I'm trying to build deb package for webkit2gtk-4.0, but still without success.
I used webkit2gtk version 2.7.3, so I don't know if it'll work with 2.6.4, but in theory it should work the same way. Did you install webkitgtk properly? I used this (in directory where I unpacked webkitgtk):

``` shell
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=/usr -DPORT=GTK ../
make 
sudo make install
```

**Comment by bilelmoussaoui** [comment]
The same thing : 
-- Granite support: OFF
-- checking for modules 'gstreamer-1.0;gtk+-3.0;glib-2.0>=2.32;gio-2.0;json-glib-1.0;webkit2gtk-4.0>=2.6.4;libxml-2.0;gdk-x11-3.0;gstreamer-video-1.0;libnotify;libsoup-2.4;gee-0.8'
--   package 'webkit2gtk-4.0>=2.6.4' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:88 (pkg_check_modules)

-- checking for modules 'gstreamer-1.0;gtk+-3.0;glib-2.0>=2.32;gio-2.0;json-glib-1.0;webkit2gtk-4.0>=2.6.4;libxml-2.0;gdk-x11-3.0;gstreamer-video-1.0;libnotify;libsoup-2.4;gee-0.8'
--   package 'webkit2gtk-4.0>=2.6.4' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:89 (pkg_check_modules)

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find Vala (missing: VALA_EXECUTABLE)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindVala.cmake:55 (find_package_handle_standard_args)
  CMakeLists.txt:98 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/bilal/photostream/build/CMakeFiles/CMakeOutput.log".

if the CMakeOutput.log might help you ; you can find it here : http://pastebin.com/tCTgdj0g
if you success on making a deb package will we see a ppa source for the app ? :D

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I guess that's the final goal, to make a repository so all users can install it through apt-get ;)
I don't know why webkit2gtk-4.0 fails (that's strange) but the string 

``` shell
Could NOT find Vala (missing: VALA_EXECUTABLE)
```

shows that there is some problems with Vala. 
Do you have vala-0.26 installed? If not, install valac-0.26 from here: https://launchpad.net/~vala-team/+archive/ubuntu/ppa

**Comment by bilelmoussaoui** [comment]
Ok, after installing vala as you said i'v less errors now (you might add it in the doc of how to build ?)
-- Granite support: OFF
-- checking for modules 'gstreamer-1.0;gtk+-3.0;glib-2.0>=2.32;gio-2.0;json-glib-1.0;webkit2gtk-4.0>=2.6.4;libxml-2.0;gdk-x11-3.0;gstreamer-video-1.0;libnotify;libsoup-2.4;gee-0.8'
--   package 'webkit2gtk-4.0>=2.6.4' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:88 (pkg_check_modules)

-- checking for modules 'gstreamer-1.0;gtk+-3.0;glib-2.0>=2.32;gio-2.0;json-glib-1.0;webkit2gtk-4.0>=2.6.4;libxml-2.0;gdk-x11-3.0;gstreamer-video-1.0;libnotify;libsoup-2.4;gee-0.8'
--   package 'webkit2gtk-4.0>=2.6.4' not found
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:283 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:337 (_pkg_check_modules_internal)
  CMakeLists.txt:89 (pkg_check_modules)

-- Found Vala: /usr/bin/valac  
-- checking for a minimum Vala version of 0.23.2
--   found Vala, version 0.26.1
-- GSettings schemas will be installed locally.
-- GSettings shemas will be compiled.
-- GSettings schemas will be installed into /usr/share/glib-2.0/schemas/
-- Configuring incomplete, errors occurred!

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui that's a progress :)
But I still can't figure out why this isn't working.
I have only one guess, maybe this has something to do with my `~./bashrc` file. I remember adding these 3 commands to `~/.bashrc` to make it work. Don't know if it will work, but this is my only guess:

``` shell
export C_INCLUDE_PATH=$C_INCLUDE_PATH:/usr/include/gstreamer-1.0:/usr/local/include/webkitgtk-4.0
export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:/usr/include/gstreamer-1.0:/usr/local/include/webkitgtk-4.0
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/x86_64-linux-gnu
```

If this won't work I don't know what will. You can try using webkit2gtk 2.7.2 instead of 2.6.4 (don't know, maybe they did something to it after 2.6.4).
Anyway, try this and post the result here. 
I will look at it later (I can't do it now because it's 3 a.m. already and I want to sleep).

**Comment by bilelmoussaoui** [comment]
I tried by adding those code lines, nothing changed.
i tried to build 2.7.2 but its not working :s i dont know how i did built 2.6.4 :/ you didnt made a deb package yet?

**Comment by bilelmoussaoui** [comment]
i've finally installed libwebkit2gtk 2.6.2, if you can make it possible to try with it ? it would be very nice!
i installed it from the gnome3 staging ppa ;)

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I tried to made deb package, it installs but the program fails to build (somehow it fails to find webkit2gtk-4.0 when linking) and I don't know why (I think I'll figure it out, but later).

As I understood, your pkg-config cannot find webkit2gtk-4.0.pc (somehow I have this file and you don't). I don't know where this file was installed in my machine (I didn't do it manually, maybe it was done by installer). Either it is not in pkgconfig default path or it doesn't exist at all (I don't know). You can try either adding path to folder containing this path to PKG_CONFIG_PATH (if this file exists) or create it yourself (mine is in `/usr/lib/x86_64-linux-gnu/pkgconfig/webkit2gtk-4.0.pc`):

``` shell
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib/x86_64-linux-gnu
includedir=${prefix}/include

Name: WebKit2
Description: Web content engine for GTK+
Version: 2.7.3
Requires: glib-2.0 gtk+-3.0 libsoup-2.4 javascriptcoregtk-4.0
Libs: -L${libdir} -lwebkit2gtk-4.0
Cflags: -I${includedir}/webkitgtk-4.0
```

To the second comment: I'm not sure if if will work (I didn't test it with previous versions), but in theory it should. You can test it yourself by editing CMakeLists.txt in the root directory of folder where you cloned my source code and replacing 2.6.4 with 2.6.2. I will change the version to 2.6.2 if your version will work.
Thanks for helping me test it! ;)

**Comment by bilelmoussaoui** [comment]
I've changed the version to 2.6.2, and finally i've built the application :D 
then when i did sudo make install i've got this : 
[100%] Built target photostream
Install the project...
-- Install configuration: ""
-- Up-to-date: /usr/share/glib-2.0/schemas/tk.itprogramming1.photostream.gschema.xml
-- Compiling GSettings schemas
-- Up-to-date: /usr/bin/photostream
CMake Error at images/cmake_install.cmake:44 (FILE):
  file INSTALL cannot find "/home/bilal/photostream/images/loading.gif".
Call Stack (most recent call first):
  cmake_install.cmake:39 (INCLUDE)

Makefile:62: recipe for target 'install' failed
make: **\* [install] Error 1
i really dont know why? 
And you're welcome !

**Comment by bilelmoussaoui** [comment]
ok i fugured out why, i think you forgot to to add loading.gif to images folder? i added an image with the same and the application is finnally installed!

**Comment by bilelmoussaoui** [comment]
I tried the application ; everything works fine until i connect to my instagram account ! then the app turn off whenever i start it again ! and when i tried to start the application from terminal ive got this error 
:9: HTML parser error : Unexpected end tag : link
af647c0/styles/activity/v1/activity.css" type="text/css" rel="stylesheet"></link
                                                                               ^

*\* (photostream:1196): ERROR **: XmlParse.vala:47: Should've not reached here.

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui Whoops, there was loading.gif before, I thought I removed it but it seems I forgot to delete it from CMakeLists.txt. Thanks for the tip, I fixed it ;)
About the second one: this error:

``` shell
:9: HTML parser error : Unexpected end tag : link
af647c0/styles/activity/v1/activity.css" type="text/css" rel="stylesheet"></link
^
```

is common, it is Xml parser warning (I cannot do anything with it because the Instagram page from where my app is getting this info: http://instagram.com/api/v1/news/inbox/ - is not valid HTML), so you can just ignore it.
The secont one(`** (photostream:1196): ERROR **: XmlParse.vala:47: Should've not reached here.`) is error I think I fixed already. I forgot to parse activities like "someone tagged you in a photo" (because there wasn't any activities like these in my news list and I couldn't parse it because I didn't know what the page will look like in this case). Now I added parsing posts like this, to in theory anything should work. Try `git pull` inside the root folder of app's source and build it again, this should work.
If not (and it will be the same error), can you save this (http://instagram.com/api/v1/news/inbox/) page and upload it somewhere?

**Comment by bilelmoussaoui** [comment]
Ok i'm going to try that , while doing "make" i've got those messages, dont know if its normal or theres something to fix so i said sharing them might be interresting ! 
warning: --save-temps has no effect when -C or --ccode is set
/home/bilal/photostream/src/Windows/LocationMapWindow.vala:288.18-288.44: warning: unhandled error `GLib.Error'
        locationList = parseLocationList(response);
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/bilal/photostream/src/Networking.vala:306.70-306.73: warning: Argument 4: Cannot pass null to non-null parameter type
    cookies.append(new Soup.Cookie("ccode", "RU", "i.instagram.com", null, -1));
                                                                     ^^^^
/home/bilal/photostream/src/Networking.vala:307.98-307.101: warning: Argument 4: Cannot pass null to non-null parameter type
    cookies.append(new Soup.Cookie("igfl", PhotoStream.App.selfUser.username, "i.instagram.com", null, -1));
                                                                                                 ^^^^
/home/bilal/photostream/src/Networking.vala:308.98-308.101: warning: Argument 4: Cannot pass null to non-null parameter type
    cookies.append(new Soup.Cookie("ds_user_id", PhotoStream.App.selfUser.id, "i.instagram.com", null, -1));
                                                                                                 ^^^^
/home/bilal/photostream/src/Networking.vala:309.101-309.104: warning: Argument 4: Cannot pass null to non-null parameter type
    cookies.append(new Soup.Cookie("ds_user", PhotoStream.App.selfUser.username, "i.instagram.com", null, -1));
                                                                                                    ^^^^
/home/bilal/photostream/src/Networking.vala:310.84-310.87: warning: Argument 4: Cannot pass null to non-null parameter type
    cookies.append(new Soup.Cookie("is_starred_enabled", "yes", "i.instagram.com", null, -1));
                                                                                   ^^^^

**Comment by bilelmoussaoui** [comment]
I still have the same problem after rebuiliding the app, you can have the file you have asked for from here 
https://www.dropbox.com/s/1arv22e09dr5075/Activity.html?dl=0

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I guess it's the messages like "Your Facebook friend %someone% has joined Instagram" (I don't have Facebook account so I couldn't test it, I didn't even know about such types of activity).
Will try to fix it, should be not so hard to fix.

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui added some code that should fix it (the problem is I cannot test it on my PC, so I don't know how this fix will behave. but I hope it'll work."

**Comment by bilelmoussaoui** [comment]
This time the app is opened , i ve received to many notifications (of all the activities, something wired nop?) 
and the applications has been closed just after...
the new bug is : 
*\* (photostream:9751): ERROR **: NewsBox.vala:192: Something wrong with file loading.

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui that's a progress.
Not sure what causes it, added some debug information. Can you pull it again, build it and post the output here?

**Comment by bilelmoussaoui** [comment]
*\* (photostream:11515): ERROR **: NewsBox.vala:192: Something wrong with file loading (): Image file '/home/bilal/.cache/photostream/avatars/' contains no data.

when i opened the folder .cache/photostream/avatars , i cant remove the files.. or anything as the only owner is root? 
![screenshot from 2015-01-11 00 58 36](https://cloud.githubusercontent.com/assets/7660997/5693754/07bcbbd8-992d-11e4-97e0-4172b3cdc1ca.png)

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui that's strange but this is not the problem, as I see problem is the filename is empty (so it points at the folder instead of image). I'l look into it.

**Comment by bilelmoussaoui** [comment]
i removed the whole cache and restart the application : 
*\* (photostream:12511): ERROR **: NewsBox.vala:192: Something wrong with file loading (http://photos-b.ak.instagram.com/hphotos-ak-xaf1/t51.2885-15/10891023_762250353829017_1849785457_s.jpg): Image file '/home/bilal/.cache/photostream/avatars/10891023_762250353829017_1849785457_s.jpg' contains no data.

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui so the avatar URL is loaded, that's okay (I thought it wasn't loaded). but somehow this single file is not loaded.
I don't know what is it, but maybe you should clear your cache (remove all files from `~/.cache/photostream` and `~/.cache/photostream/avatars` except `cookie.txt`). Maybe it can be related to the users' rights (try `sudo chmod -R 777 ~/.cache/photostream`).
I am completely not sure about this one

**Comment by bilelmoussaoui** [comment]
when i open the application as a normal user from terminal : ive got this 
*\* (photostream:15736): ERROR **: NewsBox.vala:192: Something wrong with file loading (): Image file '/home/bilal/.cache/photostream/avatars/' contains no data.
the same thing for root user :S
i dont know if i can do something else to help you debug this ?

**Comment by bilelmoussaoui** [comment]
ive rebuilt the applications after your last commit ive got some information about the notifications 
Type: fb-contact-joined/like/mention
Username: 
User profile pic: 
Post id: 
Date: 38804320
Comment:
I removed other informations but everything seems to be ok! 
the only problem is the 
*\* (photostream:17200): ERROR **: NewsBox.vala:193: Something wrong with file loading: Image file '/home/bilal/.cache/photostream/avatars/' contains no data.

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui somehow the information about such news activities is parsed wrong and I cannot understand why. I don't understand why activity type is `fb-contact-joined/like/mention`, that's strange, I didn't write something like this.
Anyway, I'll look at it later.

**Comment by bilelmoussaoui** [comment]
Noon the activity type is fb-contact-joined or like or mention , sorry i didnt explain that to you

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui Oh, that's better.
Can you post the output of the last block (this one before the error)?

**Comment by bilelmoussaoui** [comment]
Type: fb-contact-joined
Username: username(i removed it but its working!)
User profile pic: https://igcdn-photos-c-a.akamaihd.net/hphotos-ak-xaf1/t51.2885-19/10831861_319704914889610_1312219030_a.jpg
Post id: 
Date: 23273824
Comment: Your Facebook friend %USERNAME% is on Instagram as %userid%
i removed the other informations too but everything is ok !

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui so parsing is working. That's great. And the error is the same?

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui I think I figured it out, try this.
I forgot there is no post attached to such news activities and my app was trying to download image of unexisting post, this should fix it.

**Comment by bilelmoussaoui** [comment]
@serge1peshcoff sadly, still the same thing.. 
that i got when i launch the app from terminal as a normal user 
(photostream:20179): Gtk-CRITICAL *_: gtk_scrolled_window_add_with_viewport: assertion 'gtk_widget_get_parent (child) == NULL' failed
:9: HTML parser error : Unexpected end tag : link
af647c0/styles/activity/v1/activity.css" type="text/css" rel="stylesheet"></link
                                                                               ^
*_ (photostream:20179): ERROR **: NewsBox.vala:155: Something wrong with file loading.

So i tried to reclean the cache; i ve removed everything ;and then i ve got this? 
*\* (photostream:20576): ERROR **: Networking.vala:258: Something wrong with file writing: "Error opening file '/home/bilal/.cache/photostream/avatars/profile_259220806_75sq_1388631209.jpg': No such file or directory". Do the ~/.cache/ and ~/.cache/photostream directories belong to you?

Trace/breakpoint trap

**Comment by bilelmoussaoui** [comment]
i changed the permissions of the folder 
![screenshot from 2015-01-11 02 13 24](https://cloud.githubusercontent.com/assets/7660997/5693951/76056c98-9937-11e4-886e-dba159e42314.png)

And now its working :D

**Comment by serge1peshcoff** [comment]
@bil-elmoussaoui that's great news!
Now I can try to get some sleep, it's 4 a.m. already in my city.
If you'll face any bugs or errors I missed, open issues about them, I'll look at them..

**Comment by bilelmoussaoui** [comment]
This is working pretty fine for now! so i will close this.
